name: cryptoutils
version: 0.2.0+2
author: Steven Roose <stevenroose@gmail.com>
description: A crypto utility library.
homepage: https://github.com/stevenroose/dart-cryptoutils
dependencies:
  bignum: ">=0.0.4 <0.1.0"
  collection: ">=1.1.1 <2.0.0"
  zengen: ">=0.3.1 <0.4.0"

dev_dependencies:
  crypto: any
  source_gen: any
  unittest: any
